project_id = "asjhkidpuhqodryczuth"

[functions.create-mission-partner]
verify_jwt = false

[functions.send-welcome-email]
verify_jwt = false

[functions.backfill-competitor-auth]
verify_jwt = false

[functions.send-bulk-welcome]
verify_jwt = false

[functions.notify-make-youtube-published]
verify_jwt = false
